spring:
  kafka:
    bootstrap-servers:
    - ${KAFKA_SERVER:localhost:9093}
    security:
      protocol: SSL
    ssl:
      trust-store-type: JKS
      key-store-type: JKS
      protocol: SSL
      trust-store-location: "file:/Users/luizmandico/dev/spring-kafka-example/kafka-producer/docker/SSL/certs/kafka.client.truststore.jks"
      trust-store-password: 123abc
      key-store-location: "file:/Users/luizmandico/dev/spring-kafka-example/kafka-producer/docker/SSL/certs/kafka.client.keystore.jks"
      key-store-password: 123abc
      key-password: 123abc
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


server:
  port : 8081

topic:
  message: ${TOPIC_NAME:lab_topic}