apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: kafka-consumer:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
        - name: KAFKA_SERVER
          value: "kafka-broker:29092"
        - name: TOPIC_NAME
          value: "topic-kafka-lab"
        - name: KAFKA_CONSUMER_GROUP
          value: "consumer_group_lab"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
spec:
  selector:
    app: kafka-consumer
  ports:
  - port: 8081
    targetPort: 8081
