apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: kafka-producer:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_SERVER
          value: "kafka-service:9092"
        - name: TOPIC_NAME
          value: "topic-kafka-lab"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
spec:
  selector:
    app: kafka-producer
  ports:
  - port: 8080
    targetPort: 8080
